### ISSUE TITLE
Got Overwriting cache with 304 response

### ISSUE THREAD

**Issue by reggiezhang** [jaredwray/cacheable-request#28] opened 2018-03-21 12:59 UTC
with got 8.2.0
`
got.stream(imgUrl, { cache: keyv }).pipe(res);
`
records in mongodb:
`{
    "_id": ObjectID("5ab084465a793ecc436a7849"),
    "key": "cacheable-request:GET:https://farm2.staticflickr.com/1521/26180297656_675e75a2ce_h.jpg",
    "value": "{\"value\":{\"cachePolicy\":{\"v\":1,\"t\":1521635364661,\"sh\":true,\"ch\":0.1,\"imm\":86400000,\"st\":200,\"resh\":{\"date\":\"Wed, 21 Mar 2018 12:29:24 GMT\",\"connection\":\"close\",\"expires\":\"Wed, 28 Mar 2018 12:29:24 UTC\",\"cache-control\":\"max-age=604800,public\",\"via\":\"http/1.1 pc-pool116.flickr.gq1.yahoo.com (ApacheTrafficServer [cMsSfW])\",\"server\":\"ATS\",\"x-photo-farm\":\"2\",\"x-photo-farm-guess\":\"2\",\"access-control-allow-origin\":\"*\",\"access-control-allow-methods\":\"POST, GET, OPTIONS\"},\"rescc\":{\"max-age\":\"604800\",\"public\":true},\"m\":\"GET\",\"a\":true,\"reqh\":null,\"reqcc\":{}},\"url\":\"\",\"statusCode\":304,\"body\":\":base64:\"},\"expires\":null}",
    "expiresAt": null
}`

**Comment by lukechilds** [comment] 2018-03-22 04:59
Thanks, sorry missed your message on the got issue the other day. https://github.com/sindresorhus/got/issues/445#issuecomment-374155353

I've replied over there.

**Comment by pietercolpaert** [comment] 2018-05-21 16:36
Also ran into this issue with the URL https://ruben.verborgh.org.

I could not reproduce with the URL `https://farm2.staticflickr.com/1521/26180297656_675e75a2ce_h.jpg`

**Comment by szmarczak** [comment] 2018-09-03 16:07
It's not reproducible for me:

https://github.com/sindresorhus/got/issues/445#issuecomment-415956546

**Comment by TomiTakussaari** [comment] 2018-09-18 19:49
I'm also seeing this quite constantly when using Got (9.2.2) with cache.

```javascript

const agentOpts = {
  keepAlive: true
};

const agents = {
  https: new https.Agent(agentOpts),
  http: new http.Agent(agentOpts)
};

const retry = {
  retries: 2,
  methods: ['GET'],
  statusCodes: [408, 413, 429, 500, 502, 503, 504]
};

const cache = new QuickLru({maxSize: 50});

const requestConfig = {
  json: true,
  baseUrl: 'http://our-api.our-company.com/',
  headers: resolveHeaders(language),
  timeout: timeoutMs,
  agent: agents,
  retry,
  cache:  cache
};
const resolveHeaders = (language: string) => {
  //little bit more complex in reality
  const headers: { [index: string]: string } = {'accept-language': language, 'User-Agent': 'our frontend'};
  headers['x-channel'] = 'channel';
  headers['x-environment'] = 'env';
  return headers;
};
```


Our response has following headers:
```
{
 'x-correlation-id': '5613f3bc-173a-41ad-a989-e831b3993579',
  'cache-control': 'public, max-age=2',
  vary: 'Origin, Accept-Language',
  'content-language': 'fi',
  etag: 'W/"25-IXVo3gjpcqCvJf/jkWswkxjZfME"',
  date: 'Tue, 18 Sep 2018 18:39:00 GMT' 
}
```

When making first request, our backend responds with http 200, and with above headers, and everything works great.

After 2 seconds, when making another request, Got sends `if-none-match: W/"25-IXVo3gjpcqCvJf/jkWswkxjZfME"'` header, which gets 304 response, with same headers as original. 
Our code gets response body from first request, as it should.

After another 2 seconds, when making yet another request, Got sends same `if-none-match`-header, and gets another 304 response.
But this time our app gets empty response body, which is quite problematic.

Looking at cache object:

After second request:

```javascript
{'cacheable-request:GET:http://our-api.our-company.com?param=1&param2=1200&limit=30' => '{"value":{"cachePolicy":{"v":1,"t":1537299686643,"sh":true,"ch":0.1,"imm":86400000,"st":200,"resh":{"x-correlation-id":"d8dc317c-c859-4f05-91d2-90f7ba279d13","cache-control":"public, max-age=2","vary":"Origin, Accept-Language","content-language":"fi","content-type":"application/json; charset=utf-8","content-length":"39","etag":"W/\\"27-veI/wWFJ7VHyKpqkPRpX2QAqFSw\\"","date":"Tue, 18 Sep 2018 19:41:26 GMT","connection":"keep-alive"},"rescc":{"public":true,"max-age":"2"},"m":"GET","a":true,"reqh":{"user-agent":"our-app","accept-language":"fi","x-environment":"master","x-channel":"channel","accept":"application/json","accept-encoding":"gzip, deflate","if-none-match":"W/\\"27-veI/wWFJ7VHyKpqkPRpX2QAqFSw\\""},"reqcc":{}},"url":"","statusCode":200,"body":":base64:eyJyZXN1bHRzIjpbXSwibGltaXQiOjMwLCJjdXJzb3IiOjEyMDB9"},"expires":null}',
  namespace: 'cacheable-request' }
```
After third request:

```javascript
{
  'cacheable-request:GET:http://our-api.our-company.com?param=1&param2=1200&limit=30' => '{"value":{"cachePolicy":{"v":1,"t":1537299705034,"sh":true,"ch":0.1,"imm":86400000,"st":200,"resh":{"x-correlation-id":"6c5a1405-7d3b-4f27-ba64-be6038ba758f","cache-control":"public, max-age=2","vary":"Origin, Accept-Language","content-language":"fi","etag":"W/\\"27-veI/wWFJ7VHyKpqkPRpX2QAqFSw\\"","date":"Tue, 18 Sep 2018 19:41:45 GMT","connection":"keep-alive"},"rescc":{"public":true,"max-age":"2"},"m":"GET","a":true,"reqh":{"user-agent":"our-app","accept-language":"fi","x-environment":"master","x-channel":"channel","accept":"application/json","accept-encoding":"gzip, deflate","if-none-match":"W/\\"27-veI/wWFJ7VHyKpqkPRpX2QAqFSw\\""},"reqcc":{}},"url":"","statusCode":304,"body":":base64:"},"expires":null}',
  namespace: 'cacheable-request' }
```
It seems it has cached third 304 response, with no body, and returns that.

And this does happen consistently.

I presume I am doing something very wrong here, as this does seem to be quite common case, but I don't have a clue what it is right now...

I've tried to create test case for this using [nock](https://github.com/nock/nock), but it does not seem to reproduce that way for some reason.

I'll try to create test case using real server next.

**Comment by lukechilds** [comment] 2018-09-18 20:43
Thanks for the detailed feedback @TomiTakussaari 

Apologies guys, this is almost definitely an issue on my end, I just haven't had a lot of time for OSS lately. That should change very shortly.

@TomiTakussaari If you could put together a reproducible test case that would be absolutely amazing and a great help. If you're having trouble with nock could I suggest [lukechilds/create-test-server](https://github.com/lukechilds/create-test-server/) which gives you a real local HTTP server for testing.

**Comment by UltCombo** [comment] 2018-12-22 17:20
I've managed to reproduce the issue.

When `cacheable-request` performs a conditional request with `If-None-Match` header and the server sends a 304 response without `ETag` header, the cache is updated with an empty response.

According to [RFC 7232](https://httpwg.org/specs/rfc7232.html#rfc.section.4.1):

> ## 4.1. 304 Not Modified
> [...]
> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a 200 (OK) response to the same request: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.

So in this case, the server response is violating the RFC. I'm not sure how `cacheable-request` should behave, I think it's unspecified behavior.

I've reported the issue to the team responsible for the API, but seeing as it's a critical service with a legacy stack I don't expect responses to be fixed anytime soon.

Meanwhile, I've implemented an workaround in our side by wrapping the `request` function to add the missing `ETag` header before the response is processed by `cacheable-request`. This can be used with Got:

```js
const http = require('http');
const https = require('https');
const { extend } = require('got');

const got = extend({
  request: (options, callback) => {
    const request = (options.protocol === 'https:' ? https : http).request;
    return request(options, (response) => {
      if (response.statusCode === 304 && !response.headers.etag && options.headers && options.headers['if-none-match']) {
        response.headers.etag = options.headers['if-none-match'];
      }
      callback(response);
    });
  },
});
```

I'm not sure if this hack is something that you want to have in `cacheable-request`. The real problem are buggy servers sending invalid 304 responses, and the issue can be worked around in the user side if necessary.

Is this something that `cacheable-request` should handle (for compatibility with buggy servers)? What do you think? @lukechilds

**Comment by lukechilds** [comment] 2018-12-24 07:31
Thanks for looking into this @UltCombo, really appreciate that.

I'm not sure if we should try and patch things up by setting what we think the server means to respond with.

If the server isn't following the spec then it might be getting other things wrong and it's possible that it shouldn't even be returning a 304.

If this issue causes the cache to be updated with an empty response then it must be this check returning false: https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L82-L88 which happens inside the `http-cache-semantics` lib. If we decide to work around this, it should be handled there. (pinging @kornelski just so you're aware)

See if @kornelski is interested in handling this scenario. If not, thanks for sharing your solution, it'll be helpful for anyone else who comes accross this.

**Comment by kornelski** [comment] 2018-12-24 10:13
I'll have a look

**Comment by UltCombo** [comment] 2018-12-24 13:35
@lukechilds It makes perfect sense, thanks!

I would suggest to take a look at how other real-world implementations (browsers?) handle this scenario and update accordingly. @kornelski 

If browsers accept this RFC-invalid response as valid, maybe `cacheable-request` should as well, and if they don't then perhaps it should throw an error or log an warning to make this issue easier to debug?

**Comment by kornelski** [comment] 2018-12-24 14:31
The lack of etag in the response shouldn't be a problem:

https://httpwg.org/specs/rfc7234.html#rfc.section.4.3.4

>     If the new response does not include any form of validator (such as in the case where a client generates an If-Modified-Since request from a source other than the Last-Modified response header field), and there is only one stored response, and that stored response also lacks a validator, then that stored response is selected for update.

I have an `if` for that exact case in the code.

**Comment by kornelski** [comment] 2018-12-24 14:35
I think the bug is here:

https://github.com/lukechilds/cacheable-request/blob/06bd6b3bf83b82de767b6f15ac154d05fb5e2356/src/index.js#L85

it uses `response.statusCode` rather than `revalidate.statusCode`

**Comment by lukechilds** [comment] 2018-12-28 05:35
Thanks for the feedback @kornelski, greatly appreciated!

I think that was intentional, does that mean you agree with this functionality:

https://github.com/lukechilds/cacheable-request/blob/master/test/cache.js#L522-L554

@UltCombo If I whip up a branch with this change would you be willing to test it out against your problematic endpoint?

**Comment by kornelski** [comment] 2018-12-28 13:06
The cache should never expose 304 IMHO. If response is revalidated using the 304 mechanism, it means you **don't** use the 304 response, you use the original one instead.

**Comment by UltCombo** [comment] 2018-12-28 22:46
@kornelski I'm not sure if I understand correctly, please double check the emphasized part:

> If the new response does not include any form of validator (such as in the case where a client generates an If-Modified-Since request from a source other than the Last-Modified response header field), and there is only one stored response, **and that stored response also lacks a validator**, then that stored response is selected for update.

In the case I described above, the stored response has an entity-tag (which can be either a strong or weak validator), so it wouldn't satisfy the condition in the paragraph above, right?

@lukechilds I agree with Kornel, 304s should be transparent, consumer code should never receive a 304 response.

Another idea: if 304 response is "invalid" (does not satisfy revalidation criteria for any stored response), then make a new request without conditional headers. This means cacheable-request may perform 2 requests (in case it gets "invalid" 304 response for the first request), this way it would not break consumers even when servers aren't handling revalidation properly. What do you think?

**Comment by kornelski** [comment] 2018-12-28 22:59
Making two requests would be fine.

Perhaps 304 that "drops" the etag could be interpreted as if it was 304 with the same etag as before. That might be a practical bending of the RFC rules.

**Comment by UltCombo** [comment] 2018-12-28 23:36
> Perhaps 304 that "drops" the etag could be interpreted as if it was 304 with the same etag as before. That might be a practical bending of the RFC rules.

Yes, I thought the same thing. :smile:

**Comment by lukechilds** [comment] 2018-12-29 23:55
@kornelski 

>Perhaps 304 that "drops" the etag could be interpreted as if it was 304 with the same etag as before. That might be a practical bending of the RFC rules.

Do you think that logic should live in `cacheable-request` or in `http-cache-semantics`?

Thanks guys for the 304 feedback, I will get that fixed and always return the source response code.

Need to fix some tests but this branch should do that already: https://github.com/lukechilds/cacheable-request/pull/67

@UltCombo would you mind testing this branch against your problematic API (without your manual header fix) to see if it resolves the problem.

**Comment by lukechilds** [comment] 2018-12-31 02:51
Ok thanks @kornelski.

Would you mind explaining the changes in https://github.com/kornelski/http-cache-semantics/commit/7894244310c5b62b36ff8e244acd5b6b91d96d9a? I'm a little confused why:

```js
modified: true,
```

was changed to:

```
modified: response.status != 304,
```

**Comment by lukechilds** [comment] 2019-01-04 07:38
`cacheable-request@6.0.0` published which *I think* should resolve this. I'd be grateful if anyone who was encoutnering the issue could test this.

**Comment by UltCombo** [comment] 2019-01-08 22:46
I've removed my workaround, installed `cacheable-request@6.0.0` in `got@9.5.0` and the issue still persists: getting empty response body.

I just double-checked and my dependency tree is up-to-date:

```
└─┬ got@9.5.0
  └─┬ cacheable-request@6.0.0
    └── http-cache-semantics@4.0.1
```

**Comment by lukechilds** [comment] 2019-01-09 04:36
Thanks for following up @UltCombo.

I'm a little confused, should https://github.com/kornelski/http-cache-semantics/commit/7894244310c5b62b36ff8e244acd5b6b91d96d9a address this?

If not, can we implement your missing etag patch inside `http-cache-semantics` or does it need to be inside `cacheable-request`?

**Comment by lukechilds** [comment] 2019-01-09 04:39
Ahh, just noticed, that commit isn't published on npm.

@UltCombo any chance you could try pulling in the latest `http-cache-semantics` from git and trying again?

**Comment by UltCombo** [comment] 2019-01-09 13:37
@lukechilds Pulled `kornelski/http-cache-semantics#7894244310c5b62b36ff8e244acd5b6b91d96d9a`, it works now!

**Comment by kornelski** [comment] 2019-01-09 14:04
I'll make a release

**Comment by adityapatadia** [comment] 2019-01-10 10:09
Let us know if installing latest version fixes this. We can close this after success reports. I will also get it tested.

**Comment by szmarczak** [comment] 2019-01-18 11:52
> Are there any changes in GOT to fix this bug?

The latest Got uses verison `^6.0.0`. Adding it to **your** `package.json` won't fix the issue, because the older Got may use older versions of `cacheable-request` as the required version is lower.

**Comment by adityapatadia** [comment] 2019-01-18 12:12
Okay. Let me check after upgrading.

**Comment by Li0liQ** [comment] 2019-01-29 13:57
@adityapatadia Has it worked out for you? This bug blocks us from using cache with `got`.
cc @danielbentov

**Comment by szmarczak** [comment] 2019-01-29 15:09
@Li0liQ 

> This bug blocks us from using cache with got.

Do you confirm or deny the bug? Or you haven't tried out?

**Comment by Li0liQ** [comment] 2019-01-29 21:13
@szmarczak I confirm the bug (_sometimes_ on 304 `got` ends up replacing cached response with the one with empty body). I haven't tested the latest version though. The issue is, I could not reliably reproduce the bug locally, and testing it in production is not an option for me.

**Comment by szmarczak** [comment] 2019-01-29 22:01
@Li0liQ thanks for the info. If the latest version of Got fixes that (or not), please let us know :)

**Comment by adityapatadia** [comment] 2019-01-31 04:34
I am going to put logs in our production system to see if it is reproduced. I will post here in a few days.

**Comment by danielbentov** [comment] 2019-01-31 08:50
Thanks @adityapatadia

**Comment by Li0liQ** [comment] 2019-02-05 10:03
@szmarczak the latest version of `got` with `http-cache-semantics@4.0.2` still has the same issue: the cached response sometimes gets overwritten with an empty body of a 304.

**Comment by szmarczak** [comment] 2019-02-05 21:04
Hmm... Weird. I'll look at it later (again).

**Comment by adityapatadia** [comment] 2019-02-19 10:00
I have found another bug. When I do `forceRefresh=true` in options and the object is already cached, the response is always empty.

@szmarczak is this line reason behind it? https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L84

**Comment by szmarczak** [comment] 2019-02-19 10:10
> When I do `forceRefresh=true` in options and the object is already cached, the response is always empty.

Well, for me it hasn't happened yet. The test proves it:

https://github.com/lukechilds/cacheable-request/blob/645e9717aa947414cd332fc36912b7cae82ee910/test/cache.js#L563-L575

If you can give some code to reproduce the issue, that'd be great.

> is this line reason behind it?

No. It just makes sure the response isn't cached.

**Comment by CyberShadow** [comment] 2019-04-24 02:30
Please try with #77 , this looks similar to the problem I was seeing.

**Comment by adityapatadia** [comment] 2019-08-09 12:15
Culprit is this line: https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L87

It should be `if (!revalidatedPolicy.policy.modified) {`

**Comment by adityapatadia** [comment] 2019-08-09 14:24
> @szmarczak the latest version of `got` with `http-cache-semantics@4.0.2` still has the same issue: the cached response sometimes gets overwritten with an empty body of a 304.

It happens due to this issue: https://github.com/sindresorhus/got/issues/858

**Comment by jaredwray** [comment] 2022-05-19 15:34
@adityapatadia is this issue still existing and can be verified?

**Comment by adityapatadia** [comment] 2022-05-19 18:20
We have stopped using this long ago so we are not able to verify this.

**Comment by CyberShadow** [comment] 2022-05-19 18:26
> We have stopped using this long ago so we are not able to verify this.

I don't know what makes you say that.

- The patch in #77 still applies cleanly.
- The test from #77 still fails on master.

Are you looking at another pull request by mistake?

**Comment by jaredwray** [comment] 2022-07-05 17:49
Fix is in and being released under version 9 in the main branch. To be published before 7/11/2022

**Closed by jaredwray** 2022-07-05 17:49 UTC
Labels: bug

**Comment by CyberShadow** [comment] 2022-07-05 18:08
Thank you. In the future, if you use my work, I would appreciate it if you would add due credit in the commit message. Thanks!

**Comment by jaredwray** [comment] 2022-08-13 16:01
@CyberShadow - https://github.com/jaredwray/cacheable-request/releases/tag/v9.0.0

**Comment by CyberShadow** [comment] 2022-08-13 16:39
Thank you! :heart:
